services:
  - type: web
    name: pakar-matic
    runtime: docker

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        value: "base64:YOUR_KEY"