services:
  - type: web
    name: pakar-matic
    runtime: docker

    buildCommand: "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:YOUR_KEY"
      - key: APP_SERVICES_CACHE
        value: /tmp
      - key: APP_CONFIG_CACHE
        value: /tmp
      - key: APP_VIEW_CACHE
        value: /tmp